export const OPTION_BOOK_ABI = [
  {
    inputs: [
      {
        components: [
          { name: "maker", type: "address" },
          { name: "orderExpiryTimestamp", type: "uint256" },
          { name: "collateral", type: "address" },
          { name: "isCall", type: "bool" },
          { name: "priceFeed", type: "address" },
          { name: "implementation", type: "address" },
          { name: "isLong", type: "bool" },
          { name: "maxCollateralUsable", type: "uint256" },
          { name: "strikes", type: "uint256[]" },
          { name: "expiry", type: "uint256" },
          { name: "price", type: "uint256" },
          { name: "numContracts", type: "uint256" },
          { name: "extraOptionData", type: "bytes" },
        ],
        name: "order",
        type: "tuple",
      },
      { name: "signature", type: "bytes" },
      { name: "referrer", type: "address" },
    ],
    name: "fillOrder",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { name: "maker", type: "address" },
          { name: "orderExpiryTimestamp", type: "uint256" },
          { name: "collateral", type: "address" },
          { name: "isCall", type: "bool" },
          { name: "priceFeed", type: "address" },
          { name: "implementation", type: "address" },
          { name: "isLong", type: "bool" },
          { name: "maxCollateralUsable", type: "uint256" },
          { name: "strikes", type: "uint256[]" },
          { name: "expiry", type: "uint256" },
          { name: "price", type: "uint256" },
          { name: "numContracts", type: "uint256" },
          { name: "extraOptionData", type: "bytes" },
        ],
        name: "order",
        type: "tuple",
      },
      { name: "signature", type: "bytes" },
      { name: "swapRouter", type: "address" },
      { name: "swapSrcToken", type: "address" },
      { name: "swapSrcAmount", type: "uint256" },
      { name: "swapData", type: "bytes" },
      { name: "referrer", type: "address" },
    ],
    name: "swapAndFillOrder",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "token", type: "address" },
      { name: "referrer", type: "address" },
    ],
    name: "fees",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "token", type: "address" }],
    name: "claimFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "nonce", type: "uint256" },
      { indexed: true, name: "buyer", type: "address" },
      { indexed: true, name: "seller", type: "address" },
      { indexed: false, name: "optionAddress", type: "address" },
      { indexed: false, name: "premiumAmount", type: "uint256" },
      { indexed: false, name: "feeCollected", type: "uint256" },
      { indexed: false, name: "referralFeePaid", type: "uint256" },
      { indexed: false, name: "sellerWasMaker", type: "bool" },
    ],
    name: "OrderFilled",
    type: "event",
  },
] as const;

export const OPTION_FACTORY_ABI = [
  {
    inputs: [
      {
        components: [
          { name: "requester", type: "address" },
          { name: "existingOptionAddress", type: "address" },
          { name: "collateral", type: "address" },
          { name: "collateralPriceFeed", type: "address" },
          { name: "implementation", type: "address" },
          { name: "strikes", type: "uint256[]" },
          { name: "numContracts", type: "uint256" },
          { name: "requesterDeposit", type: "uint256" },
          { name: "collateralAmount", type: "uint256" },
          { name: "expiryTimestamp", type: "uint256" },
          { name: "offerEndTimestamp", type: "uint256" },
          { name: "isRequestingLongPosition", type: "bool" },
          { name: "convertToLimitOrder", type: "bool" },
          { name: "extraOptionData", type: "bytes" },
        ],
        name: "params",
        type: "tuple",
      },
      {
        components: [
          { name: "referralId", type: "uint256" },
          { name: "eventCode", type: "uint256" },
        ],
        name: "tracking",
        type: "tuple",
      },
      { name: "reservePrice", type: "uint256" },
      { name: "requesterPublicKey", type: "string" },
    ],
    name: "requestForQuotation",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "quotationId", type: "uint256" }],
    name: "quotations",
    outputs: [
      {
        components: [
          { name: "requester", type: "address" },
          { name: "existingOptionAddress", type: "address" },
          { name: "collateral", type: "address" },
          { name: "collateralPriceFeed", type: "address" },
          { name: "implementation", type: "address" },
          { name: "strikes", type: "uint256[]" },
          { name: "numContracts", type: "uint256" },
          { name: "requesterDeposit", type: "uint256" },
          { name: "collateralAmount", type: "uint256" },
          { name: "expiryTimestamp", type: "uint256" },
          { name: "offerEndTimestamp", type: "uint256" },
          { name: "isRequestingLongPosition", type: "bool" },
          { name: "convertToLimitOrder", type: "bool" },
          { name: "extraOptionData", type: "bytes" },
        ],
        name: "params",
        type: "tuple",
      },
      {
        components: [
          { name: "isActive", type: "bool" },
          { name: "currentWinner", type: "address" },
          { name: "currentBestPriceOrReserve", type: "uint256" },
          { name: "feeCollected", type: "uint256" },
          { name: "optionContract", type: "address" },
        ],
        name: "state",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getQuotationCount",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const ERC20_ABI = [
  {
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    name: "allowance",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
